version: '3.8'

services:
  app:
    build: .
    container_name: paper_filter_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - server/.env
    volumes:
      - ./server:/app/server
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
